### ISSUE TITLE
Retrieval mot de passe cryptique

### ISSUE THREAD

**Issue by mere-teresa** [afup/aperophp#100]
Je veux regen un mot de passe : l'envoi d'e-mail est bon, sauf que le mot de passe que je reçois en tant que nouveau mot de passe ressemble à une chaîne md5
Ce "mot de passe" ne fonctionne pas pour m'identifier sur le site.

exemple :  505e35c21d51c042c2c5a227b71b1cb00e3869b0

**Comment by rkueny** [comment]
Je n'ai pas pu tester le soucis en ligne, je ne reçois aucun mail alors qu'il y a bien : 

"Vous allez recevoir un email dans quelques instants pour changer de mot de passe. Si vous ne recevez pas cet email, pensez à vérifier vos indésirables."

**Comment by mikaelrandy** [comment]
Je viens de tester le process complet, aussi bien en dev qu'en prod, et je ne vois pas ce qui ne va pas.
Pour moi, tout à fonctionné.

**Comment by mikaelrandy** [comment]
Bon, en fait, je viens de voir un truc : tu as plusieurs comptes sur la même adresse email.

Du coup, c'est lié à #150
