### ISSUE TITLE
Correction des anciennes coordonnées

### ISSUE THREAD

**Issue by agallou** [afup/aperophp#133]
Certaines coordonnées GPS (latitude et longitude) ne sont pas correctes.

Cela ce voir notamment dans l'issue #101 où l'on affiche une carte des apéros.

La voici avant avoir joué le patch. Beaucoup d'apéros on lieu à paris alors que ce n'est pas le cas : 

![repart_geo_avant](https://f.cloud.github.com/assets/320372/1321995/f4d9fd56-3405-11e3-9e9f-4f2df5a1fe85.png)

Voici la carte après avoir joué le patch.

![repart_geo_apres](https://f.cloud.github.com/assets/320372/1321996/0d3feea0-3406-11e3-8090-25789eebfabc.png)

Voici comment le patch à été créé (il n'est pas forcément utile d'intégrer la commande dans le projet) : 
https://gist.github.com/agallou/495b43ac8f797dcfb6a2#file-gistfile1-php-L52

Et voici le patch à appliquer : 
https://gist.github.com/agallou/524851090fd0aa8e21f1

**Comment by agallou** [comment]
je vais essayer de retrouver la branche d'où étaient sortis les screenshots de l'issue https://github.com/afup/aperophp/issues/101 et en faire une PR. Par contre pour avoir des stats fiables, il faudrait appliquer le patch de cette issue.

**Comment by mikaelrandy** [comment]
C'est patché

**Comment by agallou** [comment]
Merci, j'ai retrouvé ma branche sur une vielle machine. J'applique quelques corrections et ferais une PR pour le #101 dans les prochains jours.
