### ISSUE TITLE
Ne pas envoyer de notification lorsque l'utilisateur choisit "Ne sera pas là"

### ISSUE THREAD

**Issue by jubianchi** [afup/aperophp#135]
Je me suis inscrit aujourd'hui à cet apéro en choisissant  "Ne sera pas là" : http://www.aperophp.net/315/view.html

j'ai reçu un mail de notification avec un rappel pour l'évènement à ajouter au calendrier.

Je ne suis pas certain que cela soit utile sachant que la personne ne viendra pas.

**Comment by mikaelrandy** [comment]
Closed by #120

**Comment by jubianchi** [comment]
:+1:

**Comment by C-Duv** [comment]
\o/ même pas besoin de faire de PR ni de test finalement :+1:
