### ISSUE TITLE
Création apéro : le sélecteur de date ne fonctionne pas

### ISSUE THREAD

**Issue by agallou** [afup/aperophp#145]
Navigateur : Chromium Version 28.0.1500.71 Ubuntu 12.04 (28.0.1500.71-0ubuntu1.12.04.1)

Erreur js :  
```
Uncaught TypeError: Cannot read property 'msie' of undefined 
```

à cause de cela, le calendrier n'est pas affiché  au clic sur l'input "jour".

![capture du 2015-08-19 12 47 34](https://cloud.githubusercontent.com/assets/320372/9354448/c2196fe4-4670-11e5-84fd-78329d91d911.png)

**Comment by mikaelkael** [comment]
Bizarre cette ligne : https://github.com/afup/aperophp/blob/master/src/Resources/views/layout.html.twig#L60, dans `{{ app.request.basepath }}`, on a une version 1.7 de jquery

**Comment by mikaelkael** [comment]
C'est le merge des stats qui a donné ça

**Comment by agallou** [comment]
@mikaelkael je corrigerais cela un soir cette semaine (vu que c'est moi qui l'ai causé)

**Comment by mikaelrandy** [comment]
Je vais travailler dessus ce soir.
Ça me donnera surement envie de reprendre les tests fonctionnels sur le projet ;)
