### ISSUE TITLE
Ajouter Montluçon dans la liste des villes

### ISSUE THREAD

**Issue by agallou** [afup/aperophp#153]
cf http://aperophp.net/382/view.html

**Comment by jacquesbh** [comment]
Resolved.

**Comment by webaaz** [comment]
Y'a du monde qui habite à Montluçon ?

Martin Supiot
06 19 03 31 27
http://www.webaaz.com
@webaaz <https://twitter.com/#%21/webaaz>

2016-03-16 12:20 GMT+01:00 Jacques Bodin-Hullin <notifications@github.com>:
