### ISSUE TITLE
Changer l'icone qui apparait lors d'un post facebook/twitter

### ISSUE THREAD

**Issue by communicationafup** [afup/aperophp#158]
Un vieux logo "apéro PHP" reprenant l'ancien logo de l'afup avec un cocktail à côté apparait lorsqu'on relaie un lien de l'apéro sur les réseaux sociaux. On peut changer ca ?
![capture d ecran 2016-11-29 a 09 10 20](https://cloud.githubusercontent.com/assets/7403715/20715473/ef148046-b614-11e6-9ad6-2077bb6999fd.png)

**Comment by agallou** [comment]
Oui, on peut changer cela. On utiliserait quel logo ?

**Comment by communicationafup** [comment]
J'essaye de dessiner quelque chose depuis tout à l'heure mais j'avoue que c'est pas mon fort...
